# v-flow configuration file
# Please ensure these paths are correct and the drives are mounted.

version: 2
locations:
  # Protected retained storage
  archive: "/Volumes/Kaung HDD"

  # Browsable root for rendered media
  exports: "/Users/kaungzinye/Desktop/Project Exports"

  # Optional locations for active Working Copies
  working:
    laptop: "/Users/kaungzinye/Desktop/Project Files"
    work_ssd: "/Volumes/T7/ActiveProjects"

settings:
  laptop_free_space_reserve_gb: 50
